name: Build and test

on:
  workflow_call:

jobs:
  build:
    name: Build Ratings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config protobuf-compiler

      - name: Check code formating
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clippy linting
        uses: giraffate/clippy-action@v1
        with:
          reporter: "github-pr-review"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Dependencies security audit
      #   uses: actions-rust-lang/audit@v1
      #   with:
      #     ignore: RUSTSEC-2023-0071 # patch not available att

      - name: Setup and Run Tests
        run: |
          cargo install cargo-make
          cargo install dotenvy --features=cli
          cargo make full-test
