name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cla:
    uses: ./.github/workflows/cla.yaml
  style-lints:
    uses: ./.github/workflows/lints.yaml
